name: jsTable
author: reednj
category: Widgets
tags: [element, interface]
docs: https://github.com/reednj/jsTable/blob/master/Docs/jsTable.md
demo: http://popacular.com/jstable/Test/demo.html
current: v0.9
